import argparse
import csv
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401


def _float(row, key, default=0.0):
    value = row.get(key)
    if value in (None, ""):
        return default
    return float(value)


def _bool(row, key):
    return str(row.get(key, "")).lower() in {"1", "true", "yes"}


def _load_rows(csv_path):
    with Path(csv_path).open(newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"trace CSV has no rows: {csv_path}")
    return rows


def _axis_limits(values, pad_ratio=0.08):
    low = min(values)
    high = max(values)
    span = high - low
    if span <= 1e-9:
        span = max(abs(high), 1.0) * 0.1
    pad = span * pad_ratio
    return low - pad, high + pad


def plot_trace(csv_path, output_path, title=None):
    rows = _load_rows(csv_path)
    steps = [_float(row, "step", idx + 1) for idx, row in enumerate(rows)]
    tcp_x = [_float(row, "tcp_x") for row in rows]
    tcp_y = [_float(row, "tcp_y") for row in rows]
    tcp_z = [_float(row, "tcp_z") for row in rows]
    target_x = _float(rows[-1], "target_x")
    target_y = _float(rows[-1], "target_y")
    target_z = _float(rows[-1], "target_z")
    distance = [_float(row, "distance") for row in rows]
    best_distance = [_float(row, "best_distance", distance[idx]) for idx, row in enumerate(rows)]
    rewards = [_float(row, "reward") for row in rows]
    joint_errors = [_float(row, "joint_target_error") for row in rows]
    success_steps = [step for step, row in zip(steps, rows) if _bool(row, "is_success_step")]

    final_distance = distance[-1]
    min_distance = min(best_distance)
    terminated = _bool(rows[-1], "terminated")
    truncated = _bool(rows[-1], "truncated")

    fig = plt.figure(figsize=(13, 8), constrained_layout=False)
    fig.suptitle(title or Path(csv_path).name, y=0.97, fontsize=16)

    ax3d = fig.add_subplot(2, 2, (1, 3), projection="3d")
    ax3d.plot(tcp_x, tcp_y, tcp_z, color="#1f77b4", linewidth=2.0, label="tcp path")
    ax3d.scatter([tcp_x[0]], [tcp_y[0]], [tcp_z[0]], color="#2ca02c", s=45, label="start")
    ax3d.scatter([tcp_x[-1]], [tcp_y[-1]], [tcp_z[-1]], color="#d62728", s=45, label="final")
    ax3d.scatter([target_x], [target_y], [target_z], color="#ff7f0e", marker="*", s=140, label="target")
    ax3d.set_xlabel("x / m")
    ax3d.set_ylabel("y / m")
    ax3d.set_zlabel("z / m")
    ax3d.set_xlim(*_axis_limits(tcp_x + [target_x]))
    ax3d.set_ylim(*_axis_limits(tcp_y + [target_y]))
    ax3d.set_zlim(*_axis_limits(tcp_z + [target_z]))
    ax3d.legend(loc="upper left", bbox_to_anchor=(0.02, 0.98))

    ax_dist = fig.add_subplot(2, 2, 2)
    ax_dist.plot(steps, distance, color="#1f77b4", label="distance")
    ax_dist.plot(steps, best_distance, color="#2ca02c", linestyle="--", label="best distance")
    if success_steps:
        ax_dist.scatter(
            success_steps,
            [distance[int(step) - 1] for step in success_steps],
            color="#ff7f0e",
            s=25,
            label="success step",
        )
    ax_dist.set_xlabel("step")
    ax_dist.set_ylabel("distance / m")
    ax_dist.grid(True, alpha=0.3)
    ax_dist.legend(loc="best")

    ax_reward = fig.add_subplot(2, 2, 4)
    ax_reward.plot(steps, rewards, color="#9467bd", label="reward")
    ax_reward.plot(steps, joint_errors, color="#8c564b", label="joint target error")
    ax_reward.set_xlabel("step")
    ax_reward.grid(True, alpha=0.3)
    ax_reward.legend(loc="upper left")

    summary = (
        f"steps={len(rows)}\n"
        f"final_distance={final_distance:.4f} m\n"
        f"best_distance={min_distance:.4f} m\n"
        f"terminated={terminated}\n"
        f"truncated={truncated}"
    )
    ax_reward.text(
        0.98,
        0.96,
        summary,
        transform=ax_reward.transAxes,
        va="top",
        ha="right",
        bbox={"boxstyle": "round,pad=0.35", "facecolor": "white", "alpha": 0.85, "edgecolor": "#cccccc"},
    )

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout(rect=(0.0, 0.0, 1.0, 0.94))
    fig.savefig(output_path, dpi=160)
    plt.close(fig)
    return output_path, len(rows), final_distance, min_distance


def main():
    parser = argparse.ArgumentParser(description="Plot a Gazebo reaching trace CSV.")
    parser.add_argument("--csv", required=True, help="Trace CSV generated by trace_gazebo_reaching.")
    parser.add_argument("--output", required=True, help="Output PNG path.")
    parser.add_argument("--title", default=None)
    args = parser.parse_args()

    output_path, steps, final_distance, best_distance = plot_trace(args.csv, args.output, args.title)
    print(f"plot={output_path}")
    print(f"steps={steps}")
    print(f"final_distance={final_distance:.4f}")
    print(f"best_distance={best_distance:.4f}")
