services:
  foxy-maxhub-a3:
    environment:
      VIDEO_DEVICE: ${VIDEO_DEVICE:-/dev/video4}
    volumes:
      - /dev/v4l:/dev/v4l:ro
    devices:
      - ${VIDEO_DEVICE:-/dev/video4}:${VIDEO_DEVICE:-/dev/video4}
